services:
  app:
    image: yorch00/webapp
    links:
      - db
    ports:
      - "80:80"
    restart: always
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro